# Generated by Django 3.0.2 on 2020-08-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='staff',
        ),
        migrations.AddField(
            model_name='appointment',
            name='abrove',
            field=models.BooleanField(default=False),
        ),
    ]
