# Generated by Django 3.0.2 on 2020-08-09 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200809_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='abrove',
            new_name='approve',
        ),
    ]
