# Generated by Django 3.0.2 on 2020-08-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200809_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='accessories',
        ),
        migrations.RemoveField(
            model_name='record',
            name='staff',
        ),
        migrations.AddField(
            model_name='record',
            name='notes',
            field=models.CharField(blank=True, max_length=120, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='record',
            name='treatment',
            field=models.TextField(blank=True, verbose_name='الأدويه'),
        ),
    ]
